eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost

server:
  port: 8301

spring:
  application:
    name: customer-service
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customer_service
    username: admin
    password: admin
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

